- .github/workflows/CD.yml
[FEAT] 이전 Docker 이미지들 제거하는 step 추가
- CD.yml에 최신 Docker 이미지를 받아 오기 전에 이전 이미지들을 삭제합니다.
#13 
> [FEAT] 이전 Docker 이미지들 제거하는 step 추가

- .github/workflows/CD.yml
[FEAT] 이전 Docker 이미지들 제거하는 step 추가
- CD.yml에 최신 Docker 이미지를 받아 오기 전에 이전 이미지들을 삭제합니다.
#13 
> [FEAT] 이전 Docker 이미지들 제거하는 step 추가 (#14)

- .github/workflows/CD.yml
[BUG] Docker 이미지 제거할 때 table 헤더 제거
- Docker 이미지 제거할 때 table 헤더 제거(참조 오류 원인 제거)
#15 
> [BUG] Docker 이미지 제거할 때 table 헤더 제거

- domain/report/service/report_consumer.py
- domain/report/service/report_consumer_impl.py
- kafka_consumer.py
[BUG] consumer가 등록 안 되는 오류 해결
- consumer가 토픽에 구독이 안 되는 문제 해결
- broker 시작 전에 consumer가 시작됐어야 했음
#18
> [BUG] consumer가 등록 안 되는 오류 해결

- domain/report/service/report_consumer.py
- domain/report/service/report_consumer_impl.py
- kafka_consumer.py
* [CHORE] handler에 message 파라미터 추가
* [FIX] broker 시작 전에 consumer 시작하게 수정
---------
[BUG] consumer가 등록 안 되는 오류 해결 (#19)
- consumer가 토픽에 구독이 안 되는 오류 해결
#18
> [BUG] consumer가 등록 안 되는 오류 해결 (#19)

- core/database/repository/crud_repository.py
- domain/comment/repository/comment_repository.py
- domain/comment/service/comment_service.py
- domain/report/service/report_consumer_impl.py
- domain/report/service/report_service.py
> [REFACTOR]: 벌크 저장 구현

- .github/workflows/CD.yml
- Dockerfile
[REFACTOR]: aws 환경 변수 제거,  postgres 환경 변수 추가
- aws 환경 변수 제거
- postgres 환경 변수 추가
- mysql 환경 변수 이름 변경
> [REFACTOR]: aws 환경 변수 제거,  postgres 환경 변수 추가

- core/kafka/message.py
- domain/report/controller/report_controller.py
- domain/report/service/report_consumer_impl.py
- external/rag/leave_analyize.py
[FEAT] 구글 액세스 토큰 입력 body에 추가
- 임시로 환경 변수로 받던 구글 액세스 토큰을 request body로 넣어주게 수정
#58 
> [FEAT] 구글 액세스 토큰 입력 body에 추가

- external/rag/leave_analyize.py
> v1.0.2 환경 변수로 토큰 받는 로직 삭제

- external/youtube/transcript_service.py
- 클라우드 ip가 유튜브한테 차단당해서 프록시 우회함
#70 
> [FEAT]: 유튜브 스크립트 프록시 우회

- external/youtube/transcript_service.py
[FIX] ip 필터링 제거
- 407 오류 발생
WARNING:urllib3.connectionpool:Retrying (Retry(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 Proxy Authentication Required')': /watch?v=_EWJ5Q0Ujbs
#72 
> [FIX] ip 필터링 제거

- .github/workflows/CD.yml
- external/rag/leave_analyize.py
- external/youtube/transcript_service.py
> [FEAT]: 프록시 환경 변수 CD에 추가

- .github/workflows/CD.yml
> v1.0.5 프록시 환경 변수 CD에서 전달

- external/youtube/transcript_service.py
* [FIX] 프록시를 통해 자막 가져오게 수정
* [CHORE] 타입 힌트 수정
* [FIX] ip 필터링 제거
* [BUILD] 프록시 환경 변수 추가
* [FEAT] ip 제한 아시아, 미국으로 제한
---------
> v1.0.6 ip 제한 아시아, 미국까지 확장

- domain/comment/service/comment_service.py
- domain/report/service/report_consumer_impl.py
- domain/report/service/report_service.py
- domain/video/service/video_service.py
[REFATCOR] 개요 페이지 리팩토링
- 컨슈머 -> 도메인 서비스 -> rag 서비스 -> llm 호출 -> 다시 도메인 서비스로 돌아와서 db 저장
- 이 패턴으로 요약, 댓글, 수치 정보 프로세스 정리
- 모든 예외 로그는 컨슈머에서 전담
- 예외 처리 각 프로세스별로 세분화
#83 
> [REFATCOR] 개요 페이지 리팩토링

- domain/report/service/report_consumer_impl.py
- domain/report/service/report_service.py
[REFACTOR] 분석 페이지 리팩토링
- 컨슈머 -> 도메인 서비스 -> rag 서비스 -> llm 호출 -> 다시 도메인 서비스로 돌아와서 db 저장
- 이 패턴으로 이탈 분석, 알고리즘 최적화 프로세스 정리
- 모든 예외 로그는 컨슈머에서 전담
- 예외 처리 각 프로세스별로 세분화
#84 
> [REFACTOR] 분석 페이지 리팩토링

- core/kafka/base_producer.py
- domain/comment/service/comment_service.py
- domain/report/service/report_consumer_impl.py
- domain/report/service/report_service.py
- domain/video/service/video_service.py
> v 1.2.0 전체 consumer 구조 리팩토링

- core/config/database_config.py
db 커넥션 시작할 때마다 +9시간 더하는 커맨드 추가
#103 
> v 1.2.2 db 저장 시간 한국으로 변경

- external/rag/leave_analyize.py
- external/rag/rag_service_impl.py
기존에 자막이 없는 영상의 경우, 에러를 던져서, FAILED 처리가 되었었습니다.
이 부분을 에러를 던지지 않고, 자막이 없는 영상 이라는 str을 반환하도록 수정하였습니다.
위 두 부분이 자막이 없는 영상으로 저장됩니다.
> [FEAT] 자막을 못 가져오는 영상의 경우 에러가 아닌, 내부 처리로 수정

- domain/video/service/video_service.py
> v 1.2.7 rich 의존성 패키지 삭제

- core/kafka/base_producer.py
- core/utils/datetime_utils.py
- domain/channel/model/channel.py
- domain/comment/model/comment.py
- domain/idea/model/idea.py
- domain/report/model/report.py
- domain/trend_keyword/model/trend_keyword.py
[CHORE] 데이터 저장할 때 한국 시간으로 저장
#125 
> [CHORE] 데이터 저장할 때 한국 시간으로 저장

- core/kafka/base_producer.py
- core/utils/datetime_utils.py
- domain/channel/model/channel.py
- domain/comment/model/comment.py
- domain/idea/model/idea.py
- domain/report/model/report.py
- domain/trend_keyword/model/trend_keyword.py
> v 1.2.8 데이터 저장할 때 한국 시간으로 저장

- external/youtube/transcript_service.py
> v 1.2.9 우회 ip 국가 한국, 일본으로 제한

- .github/workflows/CD.yml
> v 1.3.0 PostgreSQL 도커 환경으로 수정
